<?php 

namespace AgzHack\Auth\Service;

use AgzHack\Auth\Domain\Model\UserAccount;
use AgzHack\Auth\Domain\Repository\UserAccountRepository;
use Hybridauth\Hybridauth;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Security\AccountFactory;
use Neos\Flow\Security\AccountRepository;
use Neos\Flow\Security\Authentication\TokenInterface;

/**
 * @Flow\Scope("singleton")
 */
class AuthService_Original
{

    /**
     * @var UserAccountRepository
     * @Flow\Inject
     */
    protected $userAccountRepository;

    /**
     * @Flow\Inject
     * @var \Neos\Flow\Security\Context
     */
    protected $securityContext;


    protected $config = [
        //Location where to redirect users once they authenticate with Facebook
        //For this example we choose to come back to this same script
        'callback' => 'http://localhost:1003/users',

        //Facebook application credentials
        'keys' => [
            //Required: your Facebook application id
            'id' => '525134521192229',

            //Required: your Facebook application secret
            'secret' => 'b7599fe8a219de5cb573bb3ed5a90bf1'
        ]
    ];

    /**
     * @return \Hybridauth\User\Profile
     */
    public function authenticateFacebook($token)
    {
        //Instantiate Facebook's adapter directly
        $adapter = new \Hybridauth\Provider\Facebook($this->config);

        $adapter->setAccessToken(['access_token' => $token]);
        $userProfile = $adapter->getUserProfile();
        $adapter->disconnect();
        return $userProfile;
    }

    /**
     * @param string $facebookId
     * @param string $email
     * @param string $name
     * @param string $avatar
     * @return UserAccount
     * @throws \Neos\Flow\Persistence\Exception\IllegalObjectTypeException
     */
    public function getUserAccount($facebookId, $email, $name, $avatar)
    {
        $userAccount = $this->userAccountRepository->findOneByEmail($email);
        if ($userAccount instanceof UserAccount) {
            return $userAccount;
        }

        $userAccount = new UserAccount($facebookId, $email, $name, $avatar);
        $this->userAccountRepository->add($userAccount);

        return $userAccount;
    }

    /**
     * @return \Neos\Flow\Security\Account
     * @throws \Exception
     */
    public function getAuthenticatedAccount()
    {
        $tokens = $this->securityContext->getAuthenticationTokens();
        /** @var TokenInterface $token */
        foreach ($tokens as $token) {
            if ($token->isAuthenticated()) {
                return $token->getAccount();
            }
        }

        throw new \Exception("No active token", 1517142991);
    }

    /**
     * @return UserAccount
     * @throws \Exception
     * @throws \Neos\Flow\Persistence\Exception\InvalidQueryException
     */
    public function getAuthenticatedUserAccount()
    {
        $authenticatedAccount = $this->getAuthenticatedAccount();
        return $this->userAccountRepository->findOneHavingAccount($authenticatedAccount);
    }
}

#
# Start of Flow generated Proxy code
#
namespace AgzHack\Auth\Service;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * 
 * @\Neos\Flow\Annotations\Scope("singleton")
 */
class AuthService extends AuthService_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'AgzHack\Auth\Service\AuthService') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('AgzHack\Auth\Service\AuthService', $this);
        if ('AgzHack\Auth\Service\AuthService' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'userAccountRepository' => 'AgzHack\\Auth\\Domain\\Repository\\UserAccountRepository',
  'securityContext' => '\\Neos\\Flow\\Security\\Context',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'AgzHack\Auth\Service\AuthService') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('AgzHack\Auth\Service\AuthService', $this);

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->Flow_Proxy_LazyPropertyInjection('AgzHack\Auth\Domain\Repository\UserAccountRepository', 'AgzHack\Auth\Domain\Repository\UserAccountRepository', 'userAccountRepository', '6a604815fbfb388d613403fe7960f089', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('AgzHack\Auth\Domain\Repository\UserAccountRepository'); });
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\Security\Context', 'Neos\Flow\Security\Context', 'securityContext', 'f7e2ddeaebd191e228b8c2e4dc7f1f83', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Security\Context'); });
        $this->Flow_Injected_Properties = array (
  0 => 'userAccountRepository',
  1 => 'securityContext',
);
    }
}
# PathAndFilename: /var/www/lux/Packages/Application/AgzHack.Auth/Classes/Service/AuthService.php
#