<?php 

namespace AgzHack\KML\Command;

use AgzHack\KML\Domain\Builder\KMLBuilder;
use AgzHack\Lux\Domain\Model\LightMarker;
use Neos\Flow\Annotations as Flow;
use Neos\Flow\Cli\CommandController;

/**
 * @Flow\Scope("singleton")
 */
class KmlCommandController_Original extends CommandController
{
    public function testCommand()
    {
        $kmlBuilder = new KMLBuilder();
        $kmlBuilder->addMarker("ernesto", new Coordinate(1000, 2000));
        echo $kmlBuilder->getKMLXml();
    }
}

#
# Start of Flow generated Proxy code
#
namespace AgzHack\KML\Command;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * 
 * @\Neos\Flow\Annotations\Scope("singleton")
 */
class KmlCommandController extends KmlCommandController_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'AgzHack\KML\Command\KmlCommandController') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('AgzHack\KML\Command\KmlCommandController', $this);
        parent::__construct();
        if ('AgzHack\KML\Command\KmlCommandController' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'request' => 'Neos\\Flow\\Cli\\Request',
  'response' => 'Neos\\Flow\\Cli\\Response',
  'arguments' => 'Neos\\Flow\\Mvc\\Controller\\Arguments',
  'commandMethodName' => 'string',
  'objectManager' => 'Neos\\Flow\\ObjectManagement\\ObjectManagerInterface',
  'commandManager' => 'Neos\\Flow\\Cli\\CommandManager',
  'output' => 'Neos\\Flow\\Cli\\ConsoleOutput',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'AgzHack\KML\Command\KmlCommandController') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('AgzHack\KML\Command\KmlCommandController', $this);

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->injectCommandManager(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Cli\CommandManager'));
        $this->injectObjectManager(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\ObjectManagement\ObjectManagerInterface'));
        $this->Flow_Injected_Properties = array (
  0 => 'commandManager',
  1 => 'objectManager',
);
    }
}
# PathAndFilename: /var/www/lux/Packages/Application/AgzHack.KML/Classes/Command/KmlCommandController.php
#