<?php 
namespace Neos\Flow\Security\Authorization\Privilege\Entity\Doctrine;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Eel\CompilingEelParser;
use Neos\Eel\ParserException;

/**
 * A compiling expression parser
 *
 * The matcher functions will generate PHP code according to the expressions.
 * Method calls and object / array access are wrapped using the Context object.
 */
class EntityPrivilegeExpressionParser_Original extends CompilingEelParser
{
    /**
     * @param array $result
     * @param array $sub
     */
    public function NotExpression_exp(&$result, $sub)
    {
        if (!isset($result['code'])) {
            $result['code'] = '$context';
        }
        $result['code'] .= '->callAndWrap(\'notExpression\', array(' . $this->unwrapExpression($sub['code']) . '))';
    }

    /**
     * @param array $result
     * @param array $sub
     */
    public function Disjunction_rgt(&$result, $sub)
    {
        $result['code'] = '$context->callAndWrap(\'disjunction\', array(' . $this->unwrapExpression($result['code']) . ', ' . $this->unwrapExpression($sub['code']) . '))';
    }

    /**
     * @param array $result
     * @param array $sub
     */
    public function Conjunction_rgt(&$result, $sub)
    {
        $result['code'] = '$context->callAndWrap(\'conjunction\', array(' . $this->unwrapExpression($result['code']) . ', ' . $this->unwrapExpression($sub['code']) . '))';
    }

    /**
     * @param array $result
     * @param array $sub
     * @throws ParserException
     */
    public function Comparison_rgt(&$result, $sub)
    {
        $lval = $result['code'];
        $rval = $sub['code'];

        if (strpos($lval, '$context->callAndWrap(\'property\'') === false) {
            $temp = $rval;
            $rval = $lval;
            $lval = $temp;
        }

        switch ($result['comp']) {
            case '==':
                $compMethod = 'equals';
                break;
            case '!=':
                $compMethod = 'notEquals';
                break;
            case '<':
                $compMethod = 'lessThan';
                break;
            case '<=':
                $compMethod = 'lessOrEqual';
                break;
            case '>':
                $compMethod = 'greaterThan';
                break;
            case '>=':
                $compMethod = 'greaterOrEqual';
                break;
            default:
                throw new ParserException('Unexpected comparison operator "' . $result['comp'] . '"', 1344512571);
        }

        $result['code'] = $lval . '->callAndWrap(\'' . $compMethod . '\', array(' . $this->unwrapExpression($rval) . '))';
    }
}

#
# Start of Flow generated Proxy code
#
namespace Neos\Flow\Security\Authorization\Privilege\Entity\Doctrine;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * A compiling expression parser
 * 
 * The matcher functions will generate PHP code according to the expressions.
 * Method calls and object / array access are wrapped using the Context object.
 */
class EntityPrivilegeExpressionParser extends EntityPrivilegeExpressionParser_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        $arguments = func_get_args();
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $string in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        call_user_func_array('parent::__construct', $arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'tmpId' => 'integer',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /var/www/lux/Packages/Framework/Neos.Flow/Classes/Security/Authorization/Privilege/Entity/Doctrine/EntityPrivilegeExpressionParser.php
#