<?php 
namespace Neos\Flow\Persistence\Doctrine\Mapping;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Doctrine\Common\Persistence\Mapping\ReflectionService as DoctrineReflectionService;
use Neos\Flow\Reflection\ClassReflection;

/**
 * A ClassMetadata instance holds all the object-relational mapping metadata
 * of an entity and it's associations.
 */
class ClassMetadata_Original extends \Doctrine\ORM\Mapping\ClassMetadata
{
    /**
     * Gets the ReflectionClass instance of the mapped class.
     *
     * @return ClassReflection
     */
    public function getReflectionClass()
    {
        if ($this->reflClass === null) {
            $this->_initializeReflection();
        }
        return $this->reflClass;
    }

    /**
     * Initializes $this->reflClass and a number of related variables.
     *
     * @param DoctrineReflectionService $reflService
     * @return void
     */
    public function initializeReflection($reflService)
    {
        $this->_initializeReflection();
    }

    /**
     * Restores some state that can not be serialized/unserialized.
     *
     * @param DoctrineReflectionService $reflService
     * @return void
     */
    public function wakeupReflection($reflService)
    {
        parent::wakeupReflection($reflService);
        $this->reflClass = new ClassReflection($this->name);
    }

    /**
     * Initializes $this->reflClass and a number of related variables.
     *
     * @return void
     */
    protected function _initializeReflection()
    {
        $this->reflClass = new ClassReflection($this->name);
        $this->namespace = $this->reflClass->getNamespaceName();
        $this->name = $this->rootEntityName = $this->reflClass->getName();
        $this->table['name'] = $this->reflClass->getShortName();
    }
}

#
# Start of Flow generated Proxy code
#
namespace Neos\Flow\Persistence\Doctrine\Mapping;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * A ClassMetadata instance holds all the object-relational mapping metadata
 * of an entity and it's associations.
 */
class ClassMetadata extends ClassMetadata_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {


    /**
     * Autogenerated Proxy Method
     * @param string              $entityName     The name of the entity class the new instance is used for.
     * @param NamingStrategy|null $namingStrategy
     */
    public function __construct()
    {
        $arguments = func_get_args();
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $entityName in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        call_user_func_array('parent::__construct', $arguments);
    }
}
# PathAndFilename: /var/www/lux/Packages/Framework/Neos.Flow/Classes/Persistence/Doctrine/Mapping/ClassMetadata.php
#