<?php 
namespace Neos\Flow\I18n;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

/**
 * A Configuration instance represents settings to be used with the I18n
 * functionality. Examples of such settings are the locale to be used and
 * overrides for message catalogs.
 */
class Configuration_Original
{
    /**
     * @var Locale
     */
    protected $defaultLocale;

    /**
     * @var Locale
     */
    protected $currentLocale;

    /**
     * @var array
     */
    protected $fallbackRule = ['strict' => false, 'order' => []];

    /**
     * Constructs a new configuration object with the given locale identifier to
     * be used as the default locale of this configuration.
     *
     * @param string $defaultLocaleIdentifier
     * @throws Exception\InvalidLocaleIdentifierException
     */
    public function __construct($defaultLocaleIdentifier)
    {
        try {
            $this->defaultLocale = new Locale($defaultLocaleIdentifier);
        } catch (Exception\InvalidLocaleIdentifierException $exception) {
            throw new Exception\InvalidLocaleIdentifierException('The default locale identifier "' . $defaultLocaleIdentifier . '" given is invalid.', 1280935191);
        }
    }

    /**
     * Returns the default locale of this configuration.
     *
     * @return Locale
     */
    public function getDefaultLocale()
    {
        return $this->defaultLocale;
    }

    /**
     * Sets the current locale of this configuration.
     *
     * @param Locale $locale
     * @return void
     */
    public function setCurrentLocale(Locale $locale)
    {
        $this->currentLocale = $locale;
    }

    /**
     * Returns the current locale. This is the default locale if
     * no current locale has been set or the set current locale has
     * a language code of "mul".
     *
     * @return Locale
     */
    public function getCurrentLocale()
    {
        if (!$this->currentLocale instanceof Locale
            || $this->currentLocale->getLanguage() === 'mul') {
            return $this->defaultLocale;
        }
        return $this->currentLocale;
    }

    /**
     * Allows to set a fallback order for locale resolving. If not set,
     * the implicit inheritance of locales will be used. That is, if a
     * locale of en_UK is requested, matches will be searched for in en_UK
     * and en before trying the default locale configured in Flow.
     *
     * If this is given an order of [dk, za, fr_CA] a request for en_UK will
     * be looked up in en_UK, en, dk, za, fr_CA, fr before trying the default
     * locale.
     *
     * If strict flag is given in the array, the above example would instead look
     * in en_UK, dk, za, fr_CA before trying the default locale. In other words,
     * the implicit fallback is not applied to the locales in the fallback rule.
     *
     * Here is an example:
     *   array('strict' => FALSE, 'order' => array('dk', 'za'))
     *
     * @param array $fallbackRule
     */
    public function setFallbackRule(array $fallbackRule)
    {
        if (!array_key_exists('order', $fallbackRule)) {
            throw new \InvalidArgumentException('The given fallback rule did not contain an order element.', 1406710671);
        }
        if (!array_key_exists('strict', $fallbackRule)) {
            $fallbackRule['strict'] = false;
        }
        $this->fallbackRule = $fallbackRule;
    }

    /**
     * Returns the current fallback rule.
     *
     * @return array
     * @see setFallbackRule()
     */
    public function getFallbackRule()
    {
        return $this->fallbackRule;
    }
}

#
# Start of Flow generated Proxy code
#
namespace Neos\Flow\I18n;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * A Configuration instance represents settings to be used with the I18n
 * functionality. Examples of such settings are the locale to be used and
 * overrides for message catalogs.
 */
class Configuration extends Configuration_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;


    /**
     * Autogenerated Proxy Method
     * @param string $defaultLocaleIdentifier
     * @throws Exception\InvalidLocaleIdentifierException
     */
    public function __construct()
    {
        $arguments = func_get_args();
        if (!array_key_exists(0, $arguments)) throw new \Neos\Flow\ObjectManagement\Exception\UnresolvedDependenciesException('Missing required constructor argument $defaultLocaleIdentifier in class ' . __CLASS__ . '. Note that constructor injection is only support for objects of scope singleton (and this is not a singleton) – for other scopes you must pass each required argument to the constructor yourself.', 1296143788);
        call_user_func_array('parent::__construct', $arguments);
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'defaultLocale' => 'Neos\\Flow\\I18n\\Locale',
  'currentLocale' => 'Neos\\Flow\\I18n\\Locale',
  'fallbackRule' => 'array',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {

        $this->Flow_setRelatedEntities();
    }
}
# PathAndFilename: /var/www/lux/Packages/Framework/Neos.Flow/Classes/I18n/Configuration.php
#