<?php 
namespace Neos\Flow\I18n;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\I18n;

/**
 * The Detector class provides methods for automatic locale detection
 *
 * @Flow\Scope("singleton")
 * @api
 */
class Detector_Original
{
    /**
     * @var I18n\Service
     */
    protected $localizationService;

    /**
     * A collection of Locale objects representing currently installed locales,
     * in a hierarchical manner.
     *
     * @var LocaleCollection
     */
    protected $localeCollection;

    /**
     * @param I18n\Service $localizationService
     * @return void
     */
    public function injectLocalizationService(I18n\Service $localizationService)
    {
        $this->localizationService = $localizationService;
    }

    /**
     * @param LocaleCollection $localeCollection
     * @return void
     */
    public function injectLocaleCollection(LocaleCollection $localeCollection)
    {
        $this->localeCollection = $localeCollection;
    }

    /**
     * Returns best-matching Locale object based on the Accept-Language header
     * provided as parameter. System default locale will be returned if no
     * successful matches were done.
     *
     * @param string $acceptLanguageHeader The Accept-Language HTTP header
     * @return Locale Best-matching existing Locale instance
     * @api
     */
    public function detectLocaleFromHttpHeader($acceptLanguageHeader)
    {
        $acceptableLanguages = I18n\Utility::parseAcceptLanguageHeader($acceptLanguageHeader);

        if ($acceptableLanguages === false) {
            return $this->localizationService->getConfiguration()->getDefaultLocale();
        }

        foreach ($acceptableLanguages as $languageIdentifier) {
            if ($languageIdentifier === '*') {
                return $this->localizationService->getConfiguration()->getDefaultLocale();
            }

            try {
                $locale = new Locale($languageIdentifier);
            } catch (Exception\InvalidLocaleIdentifierException $exception) {
                continue;
            }

            $bestMatchingLocale = $this->localeCollection->findBestMatchingLocale($locale);

            if ($bestMatchingLocale !== null) {
                return $bestMatchingLocale;
            }
        }

        return $this->localizationService->getConfiguration()->getDefaultLocale();
    }

    /**
     * Returns best-matching Locale object based on the locale identifier
     * provided as parameter. System default locale will be returned if no
     * successful matches were done.
     *
     * @param string $localeIdentifier The locale identifier as used in Locale class
     * @return Locale Best-matching existing Locale instance
     * @api
     */
    public function detectLocaleFromLocaleTag($localeIdentifier)
    {
        try {
            return $this->detectLocaleFromTemplateLocale(new Locale($localeIdentifier));
        } catch (Exception\InvalidLocaleIdentifierException $exception) {
            return $this->localizationService->getConfiguration()->getDefaultLocale();
        }
    }

    /**
     * Returns best-matching Locale object based on the template Locale object
     * provided as parameter. System default locale will be returned if no
     * successful matches were done.
     *
     * @param Locale $locale The template Locale object
     * @return Locale Best-matching existing Locale instance
     * @api
     */
    public function detectLocaleFromTemplateLocale(Locale $locale)
    {
        $bestMatchingLocale = $this->localeCollection->findBestMatchingLocale($locale);

        if ($bestMatchingLocale !== null) {
            return $bestMatchingLocale;
        }

        return $this->localizationService->getConfiguration()->getDefaultLocale();
    }
}

#
# Start of Flow generated Proxy code
#
namespace Neos\Flow\I18n;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * The Detector class provides methods for automatic locale detection
 * @\Neos\Flow\Annotations\Scope("singleton")
 */
class Detector extends Detector_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'Neos\Flow\I18n\Detector') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Flow\I18n\Detector', $this);
        if ('Neos\Flow\I18n\Detector' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'localizationService' => 'Neos\\Flow\\I18n\\Service',
  'localeCollection' => 'Neos\\Flow\\I18n\\LocaleCollection',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'Neos\Flow\I18n\Detector') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Flow\I18n\Detector', $this);

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->injectLocalizationService(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\I18n\Service'));
        $this->injectLocaleCollection(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\I18n\LocaleCollection'));
        $this->Flow_Injected_Properties = array (
  0 => 'localizationService',
  1 => 'localeCollection',
);
    }
}
# PathAndFilename: /var/www/lux/Packages/Framework/Neos.Flow/Classes/I18n/Detector.php
#