<?php 
namespace Neos\Behat\Command;

/*
 * This file is part of the Neos.Behat package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Utility\Files;
use Neos\Flow\Cli\CommandController;

/**
 * @Flow\Scope("singleton")
 */
class BehatCommandController_Original extends CommandController
{

    /**
     * @var \Neos\Flow\Package\PackageManagerInterface
     * @Flow\Inject
     */
    protected $packageManager;

    /**
     * This command will help you to install Behat
     *
     * It will check for all necessary things to run Behat tests.
     * If you specify a Package name it will create the basis for your new
     * test.
     *
     * @return void
     */
    public function setupCommand()
    {
        $behatBuildPath = FLOW_PATH_ROOT . 'Build/Behat/';
        if (!is_dir($behatBuildPath)) {
            Files::copyDirectoryRecursively('resource://Neos.Behat/Private/Build/Behat', $behatBuildPath);
        }

        $behatBinaryPath = FLOW_PATH_ROOT . 'bin/behat';
        if (!is_file($behatBinaryPath)) {
            exec('cd "' . $behatBuildPath . '" && composer install');
            $this->outputLine();
            $this->outputLine('Installed Behat to bin/behat');
        }

        $seleniumBinaryPath = FLOW_PATH_ROOT . 'bin/selenium-server.jar';
        if (!is_file($seleniumBinaryPath)) {
            $seleniumVersion = 'selenium-server-standalone-2.53.1.jar';
            $seleniumUrl = 'http://selenium-release.storage.googleapis.com/2.53/' . $seleniumVersion;
            $returnValue = 0;
            exec('wget --quiet ' . $seleniumUrl, $output, $returnValue);
            $this->outputLine('Downloading Selenium ' . $seleniumVersion . ' to bin/selenium-server.jar...');
            if ($returnValue > 0) {
                throw new \RuntimeException('Could not download selenium from ' . $seleniumUrl . '. wget errno: ' . $returnValue);
            }
            rename(FLOW_PATH_ROOT . $seleniumVersion, FLOW_PATH_ROOT . 'bin/selenium-server.jar');
            $this->outputLine('Downloaded Selenium to bin/selenium-server.jar');
            $this->outputLine('You can execute it through: "java -jar selenium-server.jar"');
        }
    }

    /**
     * This command will help you to kickstart Behat testing for a package
     *
     * It will add a folder Tests/Behavior in your package with a default Behat setup.
     *
     * @param string $packageName The package key
     * @param string $host The base URL for the Flow application (e.g. http://example.local/)
     * @return void
     */
    public function kickstartCommand($packageName, $host)
    {
        $this->setupCommand();

        if ($this->packageManager->isPackageAvailable($packageName)) {
            $package = $this->packageManager->getPackage($packageName);

            $behaviorTestsPath = $package->getPackagePath() . 'Tests/Behavior';
            if (!is_dir($behaviorTestsPath)) {
                Files::copyDirectoryRecursively('resource://Neos.Behat/Private/Tests/Behavior', $behaviorTestsPath);
            }

            $behatConfiguration = file_get_contents($behaviorTestsPath . '/behat.yml.dist');
            $behatConfiguration = str_replace('base_url: http://localhost/', 'base_url: ' . $host, $behatConfiguration);
            file_put_contents($behaviorTestsPath . '/behat.yml', $behatConfiguration);
        }
        $this->outputLine('Behat is installed and can be used by running: "bin/behat -c Packages/Application/%s/Tests/Behavior/behat.yml"', array($packageName));
    }

}

#
# Start of Flow generated Proxy code
#
namespace Neos\Behat\Command;

use Doctrine\ORM\Mapping as ORM;
use Neos\Flow\Annotations as Flow;

/**
 * 
 * @\Neos\Flow\Annotations\Scope("singleton")
 */
class BehatCommandController extends BehatCommandController_Original implements \Neos\Flow\ObjectManagement\Proxy\ProxyInterface {

    use \Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait, \Neos\Flow\ObjectManagement\DependencyInjection\PropertyInjectionTrait;


    /**
     * Autogenerated Proxy Method
     */
    public function __construct()
    {
        if (get_class($this) === 'Neos\Behat\Command\BehatCommandController') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Behat\Command\BehatCommandController', $this);
        parent::__construct();
        if ('Neos\Behat\Command\BehatCommandController' === get_class($this)) {
            $this->Flow_Proxy_injectProperties();
        }
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __sleep()
    {
            $result = NULL;
        $this->Flow_Object_PropertiesToSerialize = array();

        $transientProperties = array (
);
        $propertyVarTags = array (
  'packageManager' => '\\Neos\\Flow\\Package\\PackageManagerInterface',
  'request' => 'Neos\\Flow\\Cli\\Request',
  'response' => 'Neos\\Flow\\Cli\\Response',
  'arguments' => 'Neos\\Flow\\Mvc\\Controller\\Arguments',
  'commandMethodName' => 'string',
  'objectManager' => 'Neos\\Flow\\ObjectManagement\\ObjectManagerInterface',
  'commandManager' => 'Neos\\Flow\\Cli\\CommandManager',
  'output' => 'Neos\\Flow\\Cli\\ConsoleOutput',
);
        $result = $this->Flow_serializeRelatedEntities($transientProperties, $propertyVarTags);
        return $result;
    }

    /**
     * Autogenerated Proxy Method
     */
    public function __wakeup()
    {
        if (get_class($this) === 'Neos\Behat\Command\BehatCommandController') \Neos\Flow\Core\Bootstrap::$staticObjectManager->setInstance('Neos\Behat\Command\BehatCommandController', $this);

        $this->Flow_setRelatedEntities();
        $this->Flow_Proxy_injectProperties();
    }

    /**
     * Autogenerated Proxy Method
     */
    private function Flow_Proxy_injectProperties()
    {
        $this->injectCommandManager(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Cli\CommandManager'));
        $this->injectObjectManager(\Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\ObjectManagement\ObjectManagerInterface'));
        $this->Flow_Proxy_LazyPropertyInjection('Neos\Flow\Package\PackageManagerInterface', 'Neos\Flow\Package\PackageManager', 'packageManager', 'b44be8eaae4695ec4f42edfbf6f8880a', function() { return \Neos\Flow\Core\Bootstrap::$staticObjectManager->get('Neos\Flow\Package\PackageManagerInterface'); });
        $this->Flow_Injected_Properties = array (
  0 => 'commandManager',
  1 => 'objectManager',
  2 => 'packageManager',
);
    }
}
# PathAndFilename: /var/www/lux/Packages/Application/Neos.Behat/Classes/Command/BehatCommandController.php
#